#!/usr/bin/env python
# coding: utf-8

# In[ ]:

def valthe(ax1, ax2, ax3, ax4, ax5, ax6, ax7, ax8, plt):
    import numpy as np
    ax1.legend(loc='lower right', fontsize = 12)
    ax1.set_title(" " , fontweight='bold', fontsize=25) 
    ax1.tick_params(axis='y', labelsize=18) 
    ax1.tick_params(axis='x', labelsize=18) 
    ax1.set_xlabel('Volumetric content [%]', fontsize = 18) 
    ax1.set_ylabel('Depth [cm]', fontsize = 18) 
    #ax1.set_yticks(np.arange(0, -120, -3))
    ax1.set_xticks(np.arange(1, 60, 5))
    ax1.grid(True) 
    #ax1.set_ylim(0, yc)  
    ax1.set_xlim(0, 60) 

    ax2.legend(loc='lower left', fontsize = 12) 
    ax2.set_title(" " , fontweight='bold', fontsize=25) 
    ax2.tick_params(axis='y', labelsize=18) 
    ax2.tick_params(axis='x', labelsize=18) 
    #ax2.set_ylabel('Depth [cm]', fontsize = 16) 
    ax2.set_xlabel('Original Bulk EC [mS/m]', fontsize = 18) 
    ax2.grid(True) 
    #ax2.set_ylim(0, yc) 
    ax2.set_xlim(0, 1.6)

    ax3.legend(loc='upper right', fontsize = 12) 
    ax3.set_title(" " , fontweight='bold', fontsize=25) 
    ax3.tick_params(axis='y', labelsize=18) 
    ax3.tick_params(axis='x', labelsize=18) 
    ax3.set_ylabel('Depth [cm]', fontsize = 18) 
    ax3.set_xlabel('Real Relative Permittivity [-]', fontsize = 18) 
    ax3.grid(True) 
    #ax3.set_ylim(0, yc) 
    ax3.set_xlim(0, 20)

    ax4.legend(loc='upper right', fontsize = 12) 
    ax4.set_title(" " , fontweight='bold', fontsize=25) 
    ax4.tick_params(axis='y', labelsize=18) 
    ax4.tick_params(axis='x', labelsize=18) 
    #ax4.set_ylabel('Depth [cm]', fontsize = 16) 
    ax4.set_xlabel('Corrected Bulk EC [mS/m]', fontsize = 18) 
    ax4.grid(True) 
    #ax4.set_ylim(0, yc) 
    ax4.set_xlim(0, 1.6)

    ax6.legend(loc='upper left', fontsize = 12) 
    ax6.set_title(" " , fontweight='bold', fontsize=25) 
    ax6.tick_params(axis='y', labelsize=18) 
    ax6.tick_params(axis='x', labelsize=18) 
    #ax6.set_ylabel('Depth [cm]', fontsize = 16) 
    ax6.set_xlabel('Water Conductivity [S/m]', fontsize = 18) 
    ax6.grid(True) 
    #ax6.set_ylim(-80, 0) 
    ax6.set_xlim(0, 0.22)
    #ax6.set_yticks(np.arange(0, 0.25, 0.02))
    ax6.set_xticks(np.arange(0, 0.22, 0.02))

    ax5.legend(loc='lower right', fontsize = 12) 
    ax5.set_title(" " , fontweight='bold', fontsize=25) 
    ax5.tick_params(axis='y', labelsize=18) 
    ax5.tick_params(axis='x', labelsize=18) 
    ax5.set_ylabel('Depth', fontsize = 16) 
    ax5.set_xlabel('Magnetic suceptibility [SI$*10^{-3}$]', fontsize = 18) 
    ax5.grid(True) 
    #ax5.set_ylim(0, 35) 
    ax5.set_xlim(0, 0.25)
    
    ax7.legend(loc='upper left', fontsize = 12) 
    #ax7.set_title("Field calibration curve " , fontweight='bold', fontsize=25) 
    ax7.tick_params(axis='y', labelsize=18) 
    ax7.tick_params(axis='x', labelsize=18) 
    ax7.set_xlabel('Real Rel. Permittivity', fontsize = 16) 
    ax7.set_ylabel('Volumetric water contect [m3/m3]', fontsize = 18) 
    ax7.grid(True) 
    ax7.set_xlim(0.001, 40) 
    ax7.set_ylim(5, 45)
    #ax7.set_yticks(np.arange(0, 0.25, 0.02))
    #ax7.set_xticks(np.arange(0, 0.22, 0.02))

    ax8.legend(loc='lower right', fontsize = 12) 
    #ax8.set_title("Field calibration curve " , fontweight='bold', fontsize=25) 
    ax8.tick_params(axis='y', labelsize=18) 
    ax8.tick_params(axis='x', labelsize=18) 
    ax8.set_xlabel('Real Rel. Permittivity', fontsize = 16) 
    ax8.set_ylabel('Volumetric water contect [m3/m3]', fontsize = 18) 
    ax8.grid(True) 
    #ax8.set_xlim(0.001, 40) 
    #ax8.set_ylim(5, 45)
    #ax8.set_yticks(np.arange(0, 0.25, 0.02))
    #ax8.set_xticks(np.arange(0, 0.22, 0.02))
    
    
def fielworkgraph(ax1, ax2, ax3, ax4, ax5, ax6, ax7, ax8, plt):
    import numpy as np
    ax1.legend(loc='upper left', fontsize = 8)
    ax1.set_title(" " , fontweight='bold', fontsize=25) 
    ax1.tick_params(axis='y', labelsize=18) 
    ax1.tick_params(axis='x', labelsize=18) 
    ax1.set_xlabel('Volumetric content [%]', fontsize = 18) 
    ax1.set_ylabel('Depth [cm]', fontsize = 18) 
    #ax1.set_yticks(np.arange(0, -120, -3))
    ax1.set_xticks(np.arange(0, 60, 5))
    ax1.grid(True) 
    #ax1.set_ylim(0, yc)  
    ax1.set_xlim(0, 60) 

    ax2.legend(loc='upper right', fontsize = 8) 
    ax2.set_title(" " , fontweight='bold', fontsize=25) 
    ax2.tick_params(axis='y', labelsize=18) 
    ax2.tick_params(axis='x', labelsize=18) 
    #ax2.set_ylabel('Depth [cm]', fontsize = 16) 
    ax2.set_xlabel('Original Bulk EC [mS/m]', fontsize = 18) 
    ax2.grid(True) 
    #ax2.set_ylim(0, yc) 
    ax2.set_xlim(0, 70)

    ax3.legend(loc='upper right', fontsize = 14) 
    ax3.set_title(" " , fontweight='bold', fontsize=25) 
    ax3.tick_params(axis='y', labelsize=18) 
    ax3.tick_params(axis='x', labelsize=18) 
    ax3.set_ylabel('Depth [cm]', fontsize = 18) 
    ax3.set_xlabel('Real Relative Permittivity [-]', fontsize = 18) 
    ax3.grid(True) 
    #ax3.set_ylim(0, yc) 
    ax3.set_xlim(0, 35)

    ax4.legend(loc='upper right', fontsize = 8) 
    ax4.set_title(" " , fontweight='bold', fontsize=25) 
    ax4.tick_params(axis='y', labelsize=18) 
    ax4.tick_params(axis='x', labelsize=18) 
    #ax4.set_ylabel('Depth [cm]', fontsize = 16) 
    ax4.set_xlabel('Corrected Bulk EC [mS/m]', fontsize = 18) 
    ax4.grid(True) 
    #ax4.set_ylim(0, yc) 
    ax4.set_xlim(0, 70)

    ax5.legend(loc='upper left', fontsize = 8) 
    ax5.set_title(" " , fontweight='bold', fontsize=25) 
    ax5.tick_params(axis='y', labelsize=18) 
    ax5.tick_params(axis='x', labelsize=18) 
    #ax5.set_ylabel('Depth [cm]', fontsize = 16) 
    ax5.set_xlabel('Water Conductivity [S/m]', fontsize = 18) 
    ax5.grid(True) 
    #ax5.set_ylim(-80, 0) 
    ax5.set_xlim(0, 0.22)
    #ax5.set_yticks(np.arange(0, 0.25, 0.02))
    ax5.set_xticks(np.arange(0, 0.22, 0.02))

    ax6.legend(loc='upper left', fontsize = 8) 
    ax6.set_title(" " , fontweight='bold', fontsize=25) 
    ax6.tick_params(axis='y', labelsize=18) 
    ax6.tick_params(axis='x', labelsize=18) 
    ax6.set_ylabel('Real Permitivitty [-]', fontsize = 16) 
    ax6.set_xlabel('Correctec Bulk Conductivity [mS/m]', fontsize = 18) 
    ax6.grid(True) 
    ax6.set_ylim(0, 35) 
    ax6.set_xlim(0, 50)
    
    ax7.legend(loc='upper left', fontsize = 8) 
    #ax7.set_title("Field calibration curve " , fontweight='bold', fontsize=25) 
    ax7.tick_params(axis='y', labelsize=18) 
    ax7.tick_params(axis='x', labelsize=18) 
    ax7.set_ylabel('Real Rel. Permittivity', fontsize = 16) 
    ax7.set_xlabel('Volumetric water contect [m3/m3]', fontsize = 18) 
    ax7.grid(True) 
    ax7.set_xlim(0.00, 70) 
    ax7.set_ylim(5, 90)
    #ax7.set_yticks(np.arange(0, 0.25, 0.02))
    #ax7.set_xticks(np.arange(0, 0.22, 0.02))

    ax8.legend(loc='lower right', fontsize = 8) 
    #ax8.set_title("Field calibration curve " , fontweight='bold', fontsize=25) 
    ax8.tick_params(axis='y', labelsize=18) 
    ax8.tick_params(axis='x', labelsize=18) 
    ax8.set_ylabel('Real Rel. Permittivity', fontsize = 16) 
    ax8.set_xlabel('Volumetric water contect [m3/m3]', fontsize = 18) 
    ax8.grid(True) 
    #ax8.set_xlim(0.001, 40) 
    #ax8.set_ylim(5, 45)
    #ax8.set_yticks(np.arange(0, 0.25, 0.02))
    #ax8.set_xticks(np.arange(0, 0.22, 0.02))

def moist_curve(axa, axb, axc, axd, axe, axf, axg, axh, plt):
    import numpy as np
    xlim = 50
    axa.legend(loc='upper left', fontsize = 14)
    axa.set_title("Water content vs Real Permittivity " , fontweight='bold', fontsize=25) 
    axa.tick_params(axis='y', labelsize=20) 
    axa.tick_params(axis='x', labelsize=20) 
    axa.set_xlabel('Volumetric water content [%]', fontsize = 22) 
    axa.set_ylabel('Real Permittivity', fontsize = 22) 
    axa.set_yticks(np.arange(0, 50, 5))
    axa.set_xticks(np.arange(0, xlim, 5))
    axa.grid(True) 
    axa.set_ylim(0, 50)  
    axa.set_xlim(0, xlim) 

    axb.legend(loc='upper left', fontsize = 14)
    axb.set_title("Water content vs Im. Permittivity " , fontweight='bold', fontsize=25) 
    axb.tick_params(axis='y', labelsize=20) 
    axb.tick_params(axis='x', labelsize=20) 
    axb.set_xlabel('Volumetric water content [%]', fontsize = 22) 
    axb.set_ylabel('Imaginary Permittivity', fontsize = 22) 
    axb.set_yticks(np.arange(0, 80, 10))
    axb.set_xticks(np.arange(0, xlim, 5))
    axb.grid(True) 
    axb.set_ylim(0, 80)  
    axb.set_xlim(0, xlim) 

    axc.legend(loc='upper left', fontsize = 14)
    axc.set_title("Water content vs EC" , fontweight='bold', fontsize=25) 
    axc.tick_params(axis='y', labelsize=20) 
    axc.tick_params(axis='x', labelsize=20) 
    axc.set_xlabel('Volumetric water content [%]', fontsize = 22) 
    axc.set_ylabel('EC [mS/m]', fontsize = 22) 
    axc.set_yticks(np.arange(0, 500, 50))
    axc.set_xticks(np.arange(0, xlim, 5))
    axc.grid(True) 
    axc.set_ylim(0, 500)  
    axc.set_xlim(0, xlim) 

    axd.legend(loc='upper left', fontsize = 14)
    axd.set_title("Water content vs EC" , fontweight='bold', fontsize=25) 
    axd.tick_params(axis='y', labelsize=20) 
    axd.tick_params(axis='x', labelsize=20) 
    axd.set_xlabel('Volumetric water content [%]', fontsize = 22) 
    axd.set_ylabel('EC [mS/m]', fontsize = 22) 
    axd.set_yticks(np.arange(0, 85, 10))
    axd.set_xticks(np.arange(0, xlim, 5))
    axd.grid(True) 
    axd.set_ylim(0, 85)  
    axd.set_xlim(0, xlim) 
    
    axe.legend(loc='upper left', fontsize = 14)
    axe.set_title("Water content vs Relaxation component " , fontweight='bold', fontsize=25) 
    axe.tick_params(axis='y', labelsize=20) 
    axe.tick_params(axis='x', labelsize=20) 
    axe.set_xlabel('Volumetric water content [%]', fontsize = 22) 
    axe.set_ylabel('Relaxation component [-]', fontsize = 22) 
    #axe.set_yticks(np.arange(0, 55, 5))
    axe.set_xticks(np.arange(0, xlim, 5))
    axe.grid(True) 
    #axe.set_ylim(0, 55)  
    axe.set_xlim(0, xlim) 
    
    axf.legend(loc='lower right', fontsize = 14)
    axf.set_title("EC vs Real permittivity" , fontweight='bold', fontsize=25) 
    axf.tick_params(axis='y', labelsize=18) 
    axf.tick_params(axis='x', labelsize=18) 
    axf.set_xlabel('EC [mS/m]', fontsize = 18) 
    axf.set_ylabel('Real Permittivity', fontsize = 18) 
    axf.set_yticks(np.arange(0, 50, 5))
    #axf.set_xticks(np.arange(0, 50, 5))
    axf.grid(True) 
    axf.set_ylim(0, 50)  
    #axf.set_xlim(0, 50) 
    
    axg.legend(loc='upper left', fontsize = 14)
    axg.set_title("Water content vs Real Permittivity " , fontweight='bold', fontsize=25) 
    axg.tick_params(axis='y', labelsize=18) 
    axg.tick_params(axis='x', labelsize=18) 
    axg.set_xlabel('Volumetric water content [%]', fontsize = 18) 
    axg.set_ylabel('Real Permittivity', fontsize = 18) 
    #axg.set_yticks(np.arange(0, 300, 20))
    axg.set_xticks(np.arange(0, 50, 5))
    axg.grid(True) 
    #axg.set_ylim(0, 80)  
    axg.set_xlim(0, 50) 
    
    #axh.legend(loc='upper left', fontsize = 14)
    #axh.set_title("Water content vs Real Permittivity " , fontweight='bold', fontsize=25) 
    #axh.tick_params(axis='y', labelsize=18) 
    #axh.tick_params(axis='x', labelsize=18) 
    #axh.set_xlabel('Volumetric water content [%]', fontsize = 18) 
    #axh.set_ylabel('Real Permittivity', fontsize = 18) 
    #axh.set_yticks(np.arange(0, 50, 5))
    #axh.set_xticks(np.arange(0, 50, 5))
    #axh.grid(True) 
    #axh.set_ylim(0, 50)  
    #axh.set_xlim(0, 50) 